### ISSUE TITLE
[Feature Request] Add dev mode

### ISSUE THREAD

**Issue by gwwatkin** [latticesurgery-com/web-ui#126]
Issue Description
-----------------
It is desirable to have a view from which we can see dev features like additional tools, logging and experimental features not stable enough to be shown to users

Proposed Solution
-----------------
Enable it with the query string `https://latticesurgery.com/online-compiler?dev=true`

**Comment by Keelando** [comment]
I see what you mean by enabling it with a query string. Perhaps I could set up a context state so that if you load the compiler page once with ?dev=true in the string, it enables dev mode and persists

**Comment by Keelando** [comment]
@gwwatkin I reopened this because I wanted to know what features you want to be hidden by dev-mode. I have just integrated the lattice "repeats" feature to dev mode, but am wondering what else? Its pretty easy to do with the react context we have set up. You just have to import the context and check whether isDevMode is enabled, and then put your code block after an if/else or isDevMode && { ... }

**Comment by gwwatkin** [comment]
I think this is good for now, will add more as we need. This issue was just for getting it started
